name: fl_state
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  rxdart: ^0.22.2
  
  bloc: ^0.15.0
  flutter_bloc: ^0.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
