name: cookbook
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  sensors: ^0.4.0+1

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: CFIdentity
      fonts:
        - asset: assets/icons/CFIdentity.ttf
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo-Regular.ttf
    - family: TextMeOne
      fonts:
        - asset: assets/fonts/TextMeOne-Regular.ttf

  uses-material-design: true

  assets:
    - assets/images/image_one.png
    - assets/images/image_two.jpg
    - assets/images/image_three.jpg