name: cookbook
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  sensors: ^0.4.0+1

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
   - family: CFIdentity
     fonts:
      - asset: assets/icons/CFIdentity.ttf

  uses-material-design: true
