name: cookbook
description: Playground via backdrop cards

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  sensors: ^0.4.0+1
  flutter_local_notifications: ^0.8.3
  flutter_bloc: ^0.21.0
  cloud_firestore: ^0.12.9+4
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.7
  rxdart: ^0.22.2
  font_awesome_flutter: ^8.5.0
  sealed_unions: ^3.0.2+2

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"

  flutter_test:
    sdk: flutter


flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icons/icon.png"
  image_path_android: "assets/icons/icon.png"
  adaptive_icon_background: "assets/icons/icon_back.png"
  adaptive_icon_foreground: "assets/icons/icon_front.png"

flutter:
  fonts:
    - family: CFIdentity
      fonts:
        - asset: assets/icons/CFIdentity.ttf
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo-Regular.ttf
    - family: TextMeOne
      fonts:
        - asset: assets/fonts/TextMeOne-Regular.ttf

  uses-material-design: true

  assets:
    - assets/images/image_one.png
    - assets/images/image_two.jpg
    - assets/images/image_three.jpg